version: '3'
services:
  mongodb:
    image: mongo:latest
    restart: always
    volumes:
      - ./scripts/mongo/init/:/docker-entrypoint-initdb.d
      - ./scripts/mongo/init:/home/mongodb
      - ./scripts/mongo/seed/:/home/mongodb/seed
      - couriers_data:/data/db
    ports:
      - '28017:27017'
    environment:
      - db_name=$db_name
      - DB_COLLECTION_NAME=$DB_COLLECTION_NAME
      - MONGO_HOSTNAME=$MONGO_HOSTNAME

  cache:
    image: redis:latest
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  api:
    container_name: couriers-db
    build:
      context: ./
    image: couriers-app
    depends_on:
      - mongodb
      - cache
    ports:
      - 3000:3000
    environment:
      - .env
    links:
      - mongodb
      - cache
    volumes:
      - ./:/src
volumes:
  couriers_data:
    driver: local
  cache:
    driver: local
